spring:
  data:
    redis:
      repositories:
        enabled: false

datasource:
  redis:
    database: 0
    master:
      host: ${REDIS_MASTER_HOST:localhost}
      port: ${REDIS_MASTER_PORT:6379}

---
spring.config.activate.on-profile: local, test

datasource:
  redis:
    master:
      host: localhost
      port: 6379

---
spring.config.activate.on-profile: dev

datasource:
  redis:
    master:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
    replicas:
      - host: ${REDIS_REPLICA_1_HOST}
        port: ${REDIS_REPLICA_1_PORT}

---
spring.config.activate.on-profile: qa

datasource:
  redis:
    master:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
    replicas:
      - host: ${REDIS_REPLICA_1_HOST}
        port: ${REDIS_REPLICA_1_PORT}

---
spring.config.activate.on-profile: prd

datasource:
  redis:
    master:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
    replicas:
      - host: ${REDIS_REPLICA_1_HOST}
        port: ${REDIS_REPLICA_1_PORT}