spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    client-id: ${spring.application.name}
    properties:
      spring.json.add.type.headers: true
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      auto:
        create.topics.enable: false
        register.schemas: false
        offset.reset: latest
      use.latest.version: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all  # At Least Once 보장
      enable-idempotence: true  # 멱등성 보장
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: loopers-default-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # 일단 String으로 받아서 직접 파싱
      properties:
        enable-auto-commit: false
        # JSON 설정 (타입 헤더 비활성화)
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual

---
spring.config.activate.on-profile: local, test

spring:
  kafka:
    bootstrap-servers: localhost:19092
    admin:
      properties:
        bootstrap.servers: kafka:9092

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd
